name: matrix strategy
on: [push]
jobs:
 node-matrix:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
     os: [ ubuntu-latest, windows-latest]
     node-version: [14,15,16]
  steps:
   - run: node -v
   - uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version }}
   
