name: Main Workflow that calls reusable-wrapper wf

on:
  workflow_dispatch:

jobs:
  call-wrapper:
    uses: ./.github/workflows/nested-reusable-wrapper.yml
    with:
      name: "Ali"
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
