name: pull_request_target add comment on pr automatically
on:
 pull_request_target:
  types: [ opened]
jobs:
  pr-comment:
   runs-on: ubuntu-latest
   steps: 
     -  name: comment on new PRS
        uses: actions/github-script@v7
        with:
         script: |
           github.rest.issues.createComment({
             onwer: context.repo.owner,
             repo: context.repo.repo,
             issue_number: context.issue.number,
             body: "Thanks for contributing!",
            });
