name: Calling Reusable Workflows.
on: [push]
  #inputs:
     # name:
     #   description: "Input description"
       # type: string
       # default: "nikita"
       # required: false
jobs:
  calling-a-reusable-wf:
    uses: nikitaks97/first-workflow/.github/workflows/reusable-workflow.yml@main
    with:
      name: nikita
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  outputs:
   runs-on: ubuntu-latest
   needs: calling-a-reusable-wf
   steps:
     - run: echo "${{ needs.calling-a-reusable-wf.outputs.date }}"
    
