name: Workflow run based in other workflow 
on: 
 workflow_run:
  workflows: [ execute workflow commands]
  types: [completed]
jobs:
  echo-string: 
   runs-on: ubuntu-latest
   steps:
     - run: echo "I was triggered because execute workflow commands succeeded"
